[firewalls]
firewall-1.lab.internal ansible_host=10.0.0.2
firewall-2.lab.internal ansible_host=10.0.0.3

[dhcp]
dhcp.lab.internal      ansible_host=10.0.0.4

[ipa]
ipa-1.lab.internal      ansible_host=10.0.0.5
ipa-2.lab.internal      ansible_host=10.0.0.6

[dns]
dns-1.lab.internal      ansible_host=10.0.0.7
dns-2.lab.internal      ansible_host=10.0.0.8

[vault]
vault-1.lab.internal      ansible_host=10.0.0.10
vault-2.lab.internal      ansible_host=10.0.0.11

[admin]
admin.lab.internal     ansible_host=10.0.0.20

[logging_server]
logs.lab.internal      ansible_host=10.0.0.30

[analytics_server]
analytics.lab.internal ansible_host=10.0.0.31

[database]
db-1.lab.internal       ansible_host=10.0.0.41
db-2.lab.internal       ansible_host=10.0.0.42

[database_witness]
db-witness.lab.internal    ansible_host=10.0.0.43

[database_backup]
db-backup-1.lab.internal    ansible_host=10.0.0.44
db-backup-2.lab.internal    ansible_host=10.0.0.45

[dns_resolvers]
dns-rslv-1.lab.internal ansible_host=10.0.0.53
dns-rslv-2.lab.internal ansible_host=10.0.0.54

[proxy]
; proxy.lab.internal     ansible_host=10.0.0.60

[apps]
; app-1.lab.internal      ansible_host=10.0.0.70

[monitored:children]
logging_server
analytics_server
firewalls
dhcp
ipa
vault
dns
dns_resolvers
database
database_witness
database_backup
admin

[monitored:vars]
ansible_user=ansible
ansible_ssh_private_key_file=/root/.ssh/ansible_ed25519
