[firewalls]
firewall1.lab.internal ansible_host=10.0.0.2
firewall2.lab.internal ansible_host=10.0.0.3

[dhcp]
dhcp.lab.internal      ansible_host=10.0.0.4

[ipa]
ipa1.lab.internal      ansible_host=10.0.0.5
ipa2.lab.internal      ansible_host=10.0.0.6

[dns]
dns1.lab.internal      ansible_host=10.0.0.7
dns2.lab.internal      ansible_host=10.0.0.8

[admin]
admin.lab.internal     ansible_host=10.0.0.20

[logging_server]
logs.lab.internal      ansible_host=10.0.0.30

[analytics_server]
analytics.lab.internal ansible_host=10.0.0.31

[database]
; db1.lab.internal       ansible_host=10.0.0.40
; db2.lab.internal       ansible_host=10.0.0.41

[dns_resolvers]
dns-rslv1.lab.internal ansible_host=10.0.0.53
dns-rslv2.lab.internal ansible_host=10.0.0.54

[proxy]
; proxy.lab.internal     ansible_host=10.0.0.60

[apps]
; app1.lab.internal      ansible_host=10.0.0.70

[monitored:children]
logging_server
analytics_server
firewalls
dhcp
ipa
dns
dns_resolvers
admin
database
proxy
apps

[monitored:vars]
ansible_user=ansible
ansible_ssh_private_key_file=/root/.ssh/ansible_ed25519
